name: ui_practice
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  email_auth: ^0.0.1+4
  stop_watch_timer: ^1.3.1
  curved_navigation_bar: ^1.0.1
  carousel_slider: ^4.0.0
  page_indicator: ^0.4.1
  charts_flutter: ^0.11.0
  dio: ^4.0.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Brandon Grotesque
      fonts:
        - asset: fonts/brandon-grotesque-light-58a8a4b38001d.otf
          weight: 700
    - family: SF Pro Text Light
      fonts:
        - asset: fonts/SF-Pro-Text-Light.otf
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-Bold.otf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
    - family: CustomGrapIcon
      fonts:
        - asset: icons/CustomGrapIcon.ttf
    - family: PieChart
      fonts:
        - asset: icons/PieChart.ttf
    - family: CustomPieChart
      fonts:
        - asset: icons/CustomPieChart.ttf
    - family: Paypal
      fonts:
        - asset: icons/PaypalIcon.ttf
    - family: Bank
      fonts:
        - asset: icons/Bank.ttf
    - family: Cheque
      fonts:
        - asset: icons/Cheque.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
